#!/bin/bash
#Sudie Roweton
#Lab 3 - Failed Login Report
#CS 3030 - Scripting

#Test for correct number of arguments

num_expected_args=1;

if [ $# -ne $num_expected_args ]; then
	echo "Usage: flog LOGFILE"
	exit 1;
fi

logfile=$1

grep 'Failed password for ' $logfile >s1out;

sed -n 's/.*Failed password for \([a-z0-9A-Z_]*\) .*/\1/p' $logfile >s2out

sort <s2out >s3out

uniq -c <s3out >s4out

sort -k1,1nr -k2,2 s4out >s5out

sed 's/invalid/\&lt;UNKNOWN\&gt;/' <s5out >s6out

now=$(date);
echo "<html>"
echo "<body><h1>Failed Login Attempts Report as of $now </h1>"

cat s6out| while read mycount myuserid; do
	printf "<br /> %'d %s\n" "$mycount" "$myuserid"
done
echo "</body> </html>"
